### ISSUE TITLE
How to test custom errors?

### ISSUE THREAD

**Issue by Oliver-Pile** [elixir-error-tracker/error-tracker#72]
Hi all.

We are making use of `ErrorTracker.report/3` to store custom errors within the tracker but are struggling to work out how to test this. 
Our current thinking is to generate the error and then assert if the error has been stored in the DB with `MyApp.Repo.all(ErrorTracker.Error)` however this always returns an empty list (Manual testing has proved it works).

Any suggestions welcome. Thanks.

**Comment by odarriba** [comment]
Hello!

There are several options I can think of, depending on your app architecture.

As of now, the ErrorTracker inserts the error on the database using the `Repo` defined. I have just tried calling `Repo.all(ErrorTracker.Error)` using our test suite and it works as expected.

However, your experience may be different depending on where are you calling the ErrorTracker from. I'm not completely sure of what happens if you for example insert the error from a GenServer (a separate process), as I don't know if the Ecto sandbox for testing may work there or not.

To be able to reproduce it we would need to know:
- from which kind of process are you reporting the error? (a controller, a module called synchronously, a Task, a GenServer...)
- do you run sync or async tests?

Another option to test this is using Telemetry, as the library emits events every time an error or occurrence is stored. However, that requires some extra code in your tests to attach to the events ([example](https://github.com/elixir-error-tracker/error-tracker/blob/main/test/support/case.ex#L41) and [example](https://github.com/elixir-error-tracker/error-tracker/blob/main/test/error_tracker/telemetry_test.exs#L16)).

**Comment by Oliver-Pile** [comment]
We are using a custom backend for `Logger` to catch the exceptions (and extract them from the metadata). This backend uses `@behaviour :gen_event` so will be some form on `GenServer`. 

This backend gets triggered for any exceptions or `Logger` calls. I've tested in a development environment with `Logger.error(...)` and that works and I can see the error in the DB with `MyApp.Repo.all(ErrorTracker.Error)`, however doing the same thing within the test doesn't work. 

The test file is `sync` and I've confirmed the logger backend is triggered and it executes the `report/3` line.

Telemetry sounds like it could work, I'll see if I can get that implemented.

Elixir: 1.17.2-opt-27
ErrorTracker: 0.2.4

**Comment by odarriba** [comment]
That may be the issue.

If the `Logger` is a separate process, you may need to allow it accessing the SQL Sandbox:
https://hexdocs.pm/ecto_sql/Ecto.Adapters.SQL.Sandbox.html#module-collaborating-processes

another option may be setting the sandbox in shared mode (which is the default in `async` tests) but I don't know the consequences of doing so in your system.

On the other hand, Telemetry events know nothing about the SQL Sandbox and should work if the ErrorTracker is able to insert the error (which I don't know if it is not allowed to access the sandbox, but I suppose on that case you would see exceptions in the console you are executing the tests).

Please, keep us updated on your findings 👀

**Comment by Oliver-Pile** [comment]
So I've tested with the different DB modes (and ultimately couldn't get it to work but here are the results). As part of the debug I viewed the DB before and after running the test. I also tried various different thing in the allow. 

**With shared: true**

1. With no `Sandbox.allow`: Run 1 & Run 2: Nothing before or after
2. With `Sandbox.allow(Logger)`: Run 1 & Run 2: Nothing before or after

**With shared: false**

   3. With no `Sandbox.allow`: Run 1 Nothing before or after. Run 2 Error Before & After
   4. With `Sandbox.allow(Logger)`: Run 1 & Run 2: Nothing before or after.

There is clearly something going on with point 3. as its not cleaning the DB between runs.

I have have managed to get it working with telemetry, checking the same fields as the DB check so that works for us.

The project is quite old so there may be something under the hood causing it to bug out with the DB. If I get a chance over the next week I'll try create a fresh project and attempt to re-produce (and let you know outcomes).

Thanks for the help.
