### ISSUE TITLE
How to do multi node (multi server) setup using Sqlite.

### ISSUE THREAD

**Issue by sksar** [elixir-error-tracker/error-tracker#98]
I have a elixir phoenix application, deployed in a load balanced manner in VPSes. 
There is no ecto repo or database required for my application so I don't have one.
So, I was thinking to use sqlite.
But, would it be possible to setup error-tracker using a multi node setup, using sqlite as the storage.

**Comment by crbelaus** [comment]
Distributed SQLite is a common problem but there are a few solutions out of there such as [LiteFS](https://github.com/superfly/litefs) (heres is the [Fly.io guides](https://fly.io/docs/litefs/)).

I'm closing this issue since distributed SQLite is more a general problem rather than something specific for the ErrorTracker.
