### ISSUE TITLE
LiveView configuration error

### ISSUE THREAD

**Issue by ShawnMcCool** [elixir-error-tracker/error-tracker#99]
Hi there, I'm running a simple Phoenix install with functioning liveviews.

When I added error tracker, and go to the /errors endpoint, the page reloads rapidly and I see the following in logs:

```elixir
[debug] LiveView session was misconfigured or the user token is outdated.

1) Ensure your session configuration in your endpoint is in a module attribute:

    @session_options [
      ...
    ]

2) Change the `plug Plug.Session` to use said attribute:

    plug Plug.Session, @session_options

3) Also pass the `@session_options` to your LiveView socket:

    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]]

4) Ensure the `protect_from_forgery` plug is in your router pipeline:

    plug :protect_from_forgery

5) Define the CSRF meta tag inside the `<head>` tag in your layout:

    <meta name="csrf-token" content={Plug.CSRFProtection.get_csrf_token()} />

6) Pass it forward in your app.js:

    let csrfToken = document.querySelector("meta[name='csrf-token']").getAttribute("content");
    let liveSocket = new LiveSocket("/live", Socket, {params: {_csrf_token: csrfToken}});
```

My socket is available at the standard /live path and largely the repository remains unchanged. I have reviewed each of the issues listed in the log and they seem fine. 

Any advice?

**Comment by odarriba** [comment]
Hello!

That is a dubug message that is usual in local development. It's a coincidence, but I saw this on my daily job this week too.

In my case, the root cause was that in `@session_options` you have set the value `secure: true`. That is not correct, as you usually access through `http://localhost:4000` (or similar, but not `https`), but it works because for most (maybe all?) browsers `locahost` is a secure place no matter the protocol. 

However, it looks like LiveView doesn't think the same and it shows you this debug message indicating that it is working but the session may not be correctly configured.

You can fix it by setting the `:secure` attribute of your session to be `true` only on `:prod` and `false` in `:dev` or `:test`.

If that's not the case, please let me know as we may need more information to find what's happening.

**Comment by ShawnMcCool** [comment]
Thank you =)
